server.port:
  8000
error:
  whitelabel:
    enabled: false

amazon:
  associate_id: habuma-20



spring.profiles.active: test

# 本地环境
---
spring:
    profiles: local
# path和file只能指定一个. 指定path的时候,文件名为spring.log
logging:
  path: /Users/xiaoyue26/learn/logs
  level:
    root: INFO
    org:
      springframework:
        security: INFO


# 测试服务环境
---
spring:
    profiles: test

logging.config: classpath:log4j2.test.yaml