server.port:
  8000
error:
  whitelabel:
    enabled: false

amazon:
  associate_id: habuma-20

info:
 contactEmail: fengmq01@fenbi.com

spring.profiles.active: local
endpoints.sensitive: true
management.context-path: /admin
management.security.enabled: true
endpoints.shutdown.enabled: true
#spring:
#  datasource:
#  url: jdbc:mysql://localhost:3306/readinglist
#  username: root
#  password: mysql

spring.jpa.hibernate.ddl-auto: create-drop
spring.datasource.primary.url: jdbc:mysql://localhost:3306/readinglist?characterEncoding=utf8&useSSL=true
spring.datasource.primary.username: root
spring.datasource.primary.password: mysql
spring.datasource.primary.driver-class-name: com.mysql.jdbc.Driver

spring.datasource.secondary.url: jdbc:mysql://localhost:3306/second_reading?characterEncoding=utf8&useSSL=true
spring.datasource.secondary.username: root
spring.datasource.secondary.password: mysql
spring.datasource.secondary.driver-class-name: com.mysql.jdbc.Driver

spring:
  redis:
    host: localhost
    password: redis123
    port: 6379
  # RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest



# Mail 配置

spring.mail.username: no-reply@fenbi.com
spring.mail.password: PyNGTB9ThPhUH9
spring.mail.port: 25 # SSL  465
spring.mail.protocol: smtp
spring.mail.host: smtp.exmail.qq.com
spring.mail.properties.mail.smtp.auth: true
#spring.mail.properties.mail.smtp.starttls.enable: true
#spring.mail.properties.mail.smtp.starttls.required: true
#spring.mail.properties.mail.smtp.checkserveridentity: true
#spring.mail.properties.mail.smtps.ssl.trust: "*"

# 本地环境
---
spring:
    profiles: local
# path和file只能指定一个. 指定path的时候,文件名为spring.log
logging.config: classpath:log4j2.dev.yaml


# 测试服务环境
---
spring:
    profiles: test

logging.config: classpath:log4j2.test.yaml

# test2
---
spring:
    profiles: test2
# path和file只能指定一个. 指定path的时候,文件名为spring.log
logging:
  path: /Users/xiaoyue26/learn/logs
  level:
    root: INFO
    org:
      springframework:
        security: INFO